In [1]:
import pandas as pd

In [2]:
def Extract(file_path):
    data = pd.read_excel(file_path,header=None)
    return data

In [3]:
def single_unpivot(df,li):
    stack_in = None
    for i in list(df.columns):
        if i in li:
            continue
        in_stack = pd.merge(df[li],df[i],left_index=True, right_index=True)
        in_stack.rename(columns = {i:0}, inplace = True)
        if stack_in is None:
            stack_in = in_stack
        else:
            stack_in = pd.concat([stack_in,in_stack])
    return stack_in

In [4]:
import re
def split_col(st):
    '''we are using regex to find the first found number to split days and time'''
    if st is None:
        return None
    k=list(re.finditer('\d+',st))[0].start()
    return [st[:k],st[k:]]

In [5]:
def days_list_fn(s):
    '''Function to convert the Mon-Sat to a list of numbers like [0,1,2,3,4,5]'''
    s = s.split("-")
    days_dict={}
    days_dict['Mon']=0
    days_dict['Tue']=1
    days_dict['Wed']=2
    days_dict['Thu']=3
    days_dict['Fri']=4
    days_dict['Sat']=5
    days_dict['Sun']=6
    days_list = list(days_dict.keys())
    if len(s)==1:
        return [days_dict[s[0]]]
    else:
        ret =[]
        for i in range(days_dict[s[0]],days_dict[s[1]]+1):
            ret.append(days_dict[days_list[i]])
        return ret

In [6]:
def convert12to24(st):
    '''Converts time like 11 pm to 23:00:00'''
    st=st.split(" ")
    
    ret=None
    if (st[1]=="am"):
        if(":" in st[0]):
            ti = st[0].split(":")
            if(int(ti[0])==12):
                ti[0]="00"
            elif(int(ti[0])<10):
                ti[0]="0"+ti[0]
            ret = ti[0]+":"+ti[1]+":00"
        else:
            if(int(st[0])==12):
                st[0]="00"
            elif(int(st[0])<10):
                st[0]="0"+st[0]
            ret=st[0]+":00:00"
    else:
        if(":" in st[0]):
            ti = st[0].split(":")
            ti[0] = str(int(ti[0])+12)
            ret = ti[0]+":"+ti[1]+":00"
        else:
            if int(st[0]) != 12: 
                st[0]=str(int(st[0])+12)
            ret=st[0]+":00:00"
    return ret
convert12to24("1:30 pm")
#10:34:23
def day_decide(day,close,time,rec):
    days_dict={}
    if "am" in close:
        day1=(int(day)+1)%7
        #print(close,day,day1,"-",time,rec)
        return day1
    else:
        return day

In [7]:
def Transform(data):
    '''Here we split time column on '/'  
    
    Eg. Mon-Thu, Sun 11:30 am - 10 pm  / Fri-Sat 11:30 am - 11 pm is split into multiple columns like
    |abc Hotel | Mon-Thu, Sun 11:30 am - 10 pm  | Fri-Sat 11:30 am - 11 pm |
    then we unpivot the columns which transform into
    |abc Hotel | Mon-Thu, Sun 11:30 am - 10 pm  |
    |abc Hotel | Fri-Sat 11:30 am - 11 pm       | 
    then we drop any columns with null data and reset the index.
    '''

    time = data[1].str.split("/",expand=True)
    data_daytime_split = pd.merge(pd.DataFrame(data[0]), time, left_index=True, right_index=True)
    data_daytime_split.rename(columns = {'0_x':'Name','0_y':0}, inplace = True)
    data_daytime_stacked = single_unpivot(data_daytime_split,["Name"])
    data_daytime_stacked = data_daytime_stacked [pd.notnull(data_daytime_stacked [0])]
    data_daytime_stacked.reset_index(inplace=True,drop=True)
    
    '''Here we split last outputed column on the first found number to seperate Days with the time  
    
    Eg. Mon-Thu, Sun 11:30 am - 10 pm is split into multiple columns like
    |Mon-Thu, Sun | 11:30 am - 10 pm  | 
    then we drop any columns with null data and reset the index.'''
    
    
    data_daytime_stacked[0]=data_daytime_stacked[0].apply(split_col)
    split = pd.DataFrame(data_daytime_stacked[0].to_list(), columns = ['Days', 'Times'])
    data_time_days_split = pd.merge(data_daytime_stacked, split, left_index=True, right_index=True)
    data_time_days_split = data_time_days_split.drop([0],axis=1)
    
    ''' Now we split the days on the delimiter ',' and then we unpivot the table
    Eg. Mon-Thu, Sun is split into mulitiple columns like
    |Mon-Thu| Sun | 
    then we unpivot the columns which transform into
    |Mon - Thu|
    |Sun|
    then we drop any columns with null data and reset the index.
    '''
    Days_sp = data_time_days_split["Days"].str.split(",",expand=True)
    data_time_days_split = pd.merge(data_time_days_split, Days_sp, left_index=True, right_index=True)
    data_time_days_split = data_time_days_split.drop(["Days"],axis=1)
    Data_time_days_stacked = single_unpivot(data_time_days_split,["Name","Times"])
    Data_time_days_stacked = Data_time_days_stacked.dropna()
    Data_time_days_stacked.reset_index(inplace=True,drop=True)
    Data_time_days_stacked[0]=Data_time_days_stacked[0].str.strip()
    Data_time_days_stacked['Day_record']=Data_time_days_stacked[0]
    
    '''
    Here we transfrom the Days Column into a list of numbers from Mon-Sun <=> 0-6 using a function. 
    Eg. Mon-Sun will first become [0,1,2,3,4,5,6] which will split into 7 different columns 
    and the we unpivot as above transformations 
    |0|1|2|3|4|5|6| will transfrom into 
    
    |0|
    |1|
    |2|
    |3|
    |4|
    |5|
    |6|
    
    then we drop the Null columns and reset the index for convience.
    '''
    
    Data_time_days_stacked[0]=Data_time_days_stacked[0].apply(days_list_fn)
    Data_time_days_stacked = Data_time_days_stacked.rename(columns={0:"Days"})
    Data_time_days_stacked = pd.merge(Data_time_days_stacked, Data_time_days_stacked.Days.apply(pd.Series), left_index=True, right_index=True)
    Data_time_days_stacked=Data_time_days_stacked.drop(["Days"],axis=1)
    Data_time_perday = single_unpivot(Data_time_days_stacked,["Name","Times","Day_record"])
    Data_time_perday = Data_time_perday.dropna()
    Data_time_perday.reset_index(inplace=True,drop=True)
    
    '''
    
    Here we transfrom the time and open and close day columns 
    we split the Time column on the delimiter '-' 
    Eg. 11:30 am - 10 pm will be split into
    |11:30 am| 10pm |
    '''
    Data_time_perday = Data_time_perday.rename(columns={0:"Open Day"})
    Data_time_perday["Close Day"] = Data_time_perday["Open Day"]
    Data_time_perday[["Open Time","Close Time"]] = Data_time_perday["Times"].str.split("-",expand=True)
    Data_time_perday["Open Time"]=Data_time_perday["Open Time"].str.strip()
    Data_time_perday["Close Time"]=Data_time_perday["Close Time"].str.strip()
    
    '''
    Here we calulate the close day using day decide function. 
    If the close day has am which means it is open midnight the next day. We change the Close Day to next day 
    
    We tranform the Close time column
    Them we transform the Open and Close time into 24hrs time.
    eg. 11:30pm <=> 23:00:00
    
    '''
    
    Data_time_perday['Close Day'] = Data_time_perday.apply(lambda x : day_decide(x["Close Day"], x["Close Time"],x["Times"],x["Day_record"]), axis=1)
    Data_time_perday['Close Time']=Data_time_perday['Close Time'].apply(convert12to24)
    Data_time_perday['Open Time']=Data_time_perday['Open Time'].apply(convert12to24)
    Data_time_perday['Open Time']=pd.to_datetime(Data_time_perday['Open Time'], format='%H:%M:%S').dt.time
    Data_time_perday['Close Time']=pd.to_datetime(Data_time_perday['Close Time'], format='%H:%M:%S').dt.time
    Data_time_perday["Close Day"] = Data_time_perday["Close Day"].astype(str)
    Data_time_perday["Open Day"] = Data_time_perday["Open Day"].astype(str)
    return Data_time_perday

In [8]:
Extracted_Data = Extract(r"C:\Users\allav\Downloads\restaraunts-opening-hour.xlsx")
Extracted_Data

,0,1
0,Kushi Tsuru,Mon-Sun 11:30 am - 9 pm
1,Osakaya Restaurant,"Mon-Thu, Sun 11:30 am - 9 pm / Fri-Sat 11:30 ..."
2,The Stinking Rose,"Mon-Thu, Sun 11:30 am - 10 pm / Fri-Sat 11:30..."
3,McCormick & Kuleto's,"Mon-Thu, Sun 11:30 am - 10 pm / Fri-Sat 11:30..."
4,Mifune Restaurant,Mon-Sun 11 am - 10 pm
5,The Cheesecake Factory,Mon-Thu 11 am - 11 pm / Fri-Sat 11 am - 12:30...
6,New Delhi Indian Restaurant,Mon-Sat 11:30 am - 10 pm / Sun 5:30 pm - 10 pm
7,Iroha Restaurant,"Mon-Thu, Sun 11:30 am - 9:30 pm / Fri-Sat 11:..."
8,Rose Pistola,Mon-Thu 11:30 am - 10 pm / Fri-Sun 11:30 am -...
9,Alioto's Restaurant,Mon-Sun 11 am - 11 pm
10,Canton Seafood & Dim Sum Restaurant,Mon-Fri 10:30 am - 9:30 pm / Sat-Sun 10 am - ...
11,All Season Restaurant,Mon-Fri 10 am - 9:30 pm / Sat-Sun 9:30 am - 9...
12,Bombay Indian Restaurant,Mon-Sun 11:30 am - 10:30 pm
13,Sam's Grill & Seafood Restaurant,Mon-Fri 11 am - 9 pm / Sat 5 pm - 9 pm
14,2G Japanese Brasserie,"Mon-Thu, Sun 11 am - 10 pm / Fri-Sat 11 am - ..."
15,Restaurant Lulu,"Mon-Thu, Sun 11:30 am - 9 pm / Fri-Sat 11:30 ..."
16,Sudachi,Mon-Wed 5 pm - 12:30 am / Thu-Fri 5 pm - 1:30...
17,Hanuri,Mon-Sun 11 am - 12 am
18,Herbivore,"Mon-Thu, Sun 9 am - 10 pm / Fri-Sat 9 am - 11 pm"
19,Penang Garden,Mon-Thu 11 am - 10 pm / Fri-Sat 10 am - 10:30...
20,John's Grill,Mon-Sat 11 am - 10 pm / Sun 12 pm - 10 pm
21,Quan Bac,Mon-Sun 11 am - 10 pm
22,Bamboo Restaurant,Mon-Sat 11 am - 12 am / Sun 12 pm - 12 am
23,Burger Bar,"Mon-Thu, Sun 11 am - 10 pm / Fri-Sat 11 am - ..."
24,Blu Restaurant,Mon-Fri 11:30 am - 10 pm / Sat-Sun 7 am - 3 pm
25,Naan 'N' Curry,Mon-Sun 11 am - 4 am
26,Shanghai China Restaurant,Mon-Sun 11 am - 9:30 pm
27,Tres,"Mon-Thu, Sun 11:30 am - 10 pm / Fri-Sat 11:30..."
28,Isobune Sushi,Mon-Sun 11:30 am - 9:30 pm
29,Viva Pizza Restaurant,Mon-Sun 11 am - 12 am
30,Far East Cafe,Mon-Sun 11:30 am - 10 pm
31,Parallel 37,Mon-Sun 11:30 am - 10 pm
32,Bai Thong Thai Cuisine,Mon-Sat 11 am - 11 pm / Sun 11 am - 10 pm
33,Alhamra,Mon-Sun 11 am - 11 pm
34,A-1 Cafe Restaurant,"Mon, Wed-Sun 11 am - 10 pm"
35,Nick's Lighthouse,Mon-Sun 11 am - 10:30 pm
36,Paragon Restaurant & Bar,Mon-Fri 11:30 am - 10 pm / Sat 5:30 pm - 10 pm
37,Chili Lemon Garlic,Mon-Fri 11 am - 10 pm / Sat-Sun 5 pm - 10 pm
38,Bow Hon Restaurant,Mon-Sun 11 am - 10:30 pm
39,San Dong House,Mon-Sun 11 am - 11 pm
40,Thai Stick Restaurant,Mon-Sun 11 am - 1 am
41,Cesario's,"Mon-Thu, Sun 11:30 am - 10 pm / Fri-Sat 11:30..."
42,Colombini Italian Cafe Bistro,Mon-Fri 12 pm - 10 pm / Sat-Sun 5 pm - 10 pm
43,Sabella & La Torre,"Mon-Thu, Sun 10 am - 10:30 pm / Fri-Sat 10 am..."
44,Soluna Cafe and Lounge,Mon-Fri 11:30 am - 10 pm / Sat 5 pm - 10 pm
45,Tong Palace,Mon-Fri 9 am - 9:30 pm / Sat-Sun 9 am - 10 pm
46,India Garden Restaurant,Mon-Sun 10 am - 11 pm
47,Sapporo-Ya Japanese Restaurant,Mon-Sat 11 am - 11 pm / Sun 11 am - 10:30 pm
48,Santorini's Mediterranean Cuisine,Mon-Sun 8 am - 10:30 pm
49,Kyoto Sushi,Mon-Thu 11 am - 10:30 pm / Fri 11 am - 11 pm ...
50,Marrakech Moroccan Restaurant,Mon-Sun 5:30 pm - 2 am

In [9]:
Transformed_Data =Transform(Extracted_Data)
Transformed_Data

,Name,Times,Day_record,Open Day,Close Day,Open Time,Close Time
0,Kushi Tsuru,11:30 am - 9 pm,Mon-Sun,0.0,0.0,11:30:00,21:00:00
1,Osakaya Restaurant,11:30 am - 9 pm,Mon-Thu,0.0,0.0,11:30:00,21:00:00
2,The Stinking Rose,11:30 am - 10 pm,Mon-Thu,0.0,0.0,11:30:00,22:00:00
3,McCormick & Kuleto's,11:30 am - 10 pm,Mon-Thu,0.0,0.0,11:30:00,22:00:00
4,Mifune Restaurant,11 am - 10 pm,Mon-Sun,0.0,0.0,11:00:00,22:00:00
...,...,...,...,...,...,...,...
348,San Dong House,11 am - 11 pm,Mon-Sun,6.0,6.0,11:00:00,23:00:00
349,Thai Stick Restaurant,11 am - 1 am,Mon-Sun,6.0,0.0,11:00:00,01:00:00
350,India Garden Restaurant,10 am - 11 pm,Mon-Sun,6.0,6.0,10:00:00,23:00:00
351,Santorini's Mediterranean Cuisine,8 am - 10:30 pm,Mon-Sun,6.0,6.0,08:00:00,22:30:00
352,Marrakech Moroccan Restaurant,5:30 pm - 2 am,Mon-Sun,6.0,0.0,17:30:00,02:00:00

In [10]:
import datetime
date_now = datetime.datetime.now()#(2022, 11, ,18, 0, 0, 0)

In [11]:
def Analysis(Data_time_perday,date):   
    
    '''
    Logic we are tying to write is.
    
    The input time will fall in one in 3 conditions
    
    day-1 open time ---------time---------- day close time
    day   open time ---------time---------- day close time
    day   open time ---------time---------- day+1 close time
    
    if we find the restaurant satisfying the above condition is the desired result.
    
    
    '''
    day = date.weekday()
    time = date.time()
    print(date)
    day_s=(day-1)
    day_a=(day+1)%7
    if(day_s<0):
        day_s=6
    day = str(day)+".0"
    day_s = str(day_s)+".0"
    day_a = str(day_a)+".0"

    print(day_s,day,day_a)
    
    
    o_d= Data_time_perday["Open Day"]
    c_d= Data_time_perday["Close Day"]
    
    
    '''Below variables are used to check the day logic'''
    a = Data_time_perday["Open Day"]==day 
    b = Data_time_perday["Close Day"]==day
    c = Data_time_perday["Open Day"]==day_s
    d = Data_time_perday["Close Day"]==day
    e = Data_time_perday["Open Day"]==day
    f = Data_time_perday["Close Day"]==day_a
    
    '''Below variables are used to check the time logic'''
    
    at= Data_time_perday["Open Time"] <= time
    bt= Data_time_perday["Close Time"] >= time
    at1= ((o_d<c_d)|(c_d.str.contains('0.0') & o_d.str.contains('6.0'))) | at
    bt1= Data_time_perday["Close Time"] >= time
    at2= Data_time_perday["Open Time"] <= time
    bt2= ((o_d<c_d)|(c_d.str.contains('0.0') & o_d.str.contains('6.0'))) | bt
    
    '''We use day and time of day-1,day,day+1 variables and return the rows which return true'''
    
    return Data_time_perday[((a&b&at&bt))|(c&d&at1&bt1)|(e&f&at2&bt2)]

def main(file_path,date):
    ret = Analysis(Transform(Extract(r"C:\Users\allav\Downloads\restaraunts-opening-hour.xlsx")),date)
    print(ret.shape)
    return ret["Name"].tolist()

In [12]:
main(r"C:\Users\allav\Downloads\restaraunts-opening-hour.xlsx",date_now)

2022-11-05 17:50:04.127880
4.0 5.0 6.0
(50, 7)

['Canton Seafood & Dim Sum Restaurant',
 'All Season Restaurant',
 "Sam's Grill & Seafood Restaurant",
 'Paragon Restaurant & Bar',
 'Chili Lemon Garlic',
 'Colombini Italian Cafe Bistro',
 'Soluna Cafe and Lounge',
 'Tong Palace',
 'Sudachi',
 'Kyoto Sushi',
 'Osakaya Restaurant',
 'The Stinking Rose',
 "McCormick & Kuleto's",
 'The Cheesecake Factory',
 'Iroha Restaurant',
 'Rose Pistola',
 '2G Japanese Brasserie',
 'Restaurant Lulu',
 'Herbivore',
 'Penang Garden',
 'Burger Bar',
 'Tres',
 "Cesario's",
 'Sabella & La Torre',
 'A-1 Cafe Restaurant',
 'Kushi Tsuru',
 'Mifune Restaurant',
 'New Delhi Indian Restaurant',
 "Alioto's Restaurant",
 'Bombay Indian Restaurant',
 'Hanuri',
 "John's Grill",
 'Quan Bac',
 'Bamboo Restaurant',
 "Naan 'N' Curry",
 'Shanghai China Restaurant',
 'Isobune Sushi',
 'Viva Pizza Restaurant',
 'Far East Cafe',
 'Parallel 37',
 'Bai Thong Thai Cuisine',
 'Alhamra',
 "Nick's Lighthouse",
 'Bow Hon Restaurant',
 'San Dong House',
 'Thai Stick Restaurant',
 'India Garden Restaurant',
 'Sapporo-Ya Japanese Restaurant',
 "Santorini's Mediterranean Cuisine",
 'Marrakech Moroccan Restaurant']